### ISSUE TITLE
EDD-EDMC-1.2.0.exe download blocked by Chrome

### ISSUE THREAD

**Issue by booiiing** [EDDiscovery/EDD-EDMC#4]
Chrome is blocking the download as "potentially harmful". More information is here: https://developers.google.com/search/docs/advanced/security/malware?visit_id=637496131615705880-2107114719&rd=1

I guess it's because the binary is not signed, but have to admit that I didn't check that.

**Comment by robbyxp1** [comment]
Its because of the version of the Python it uses is somehow being disliked by some, not all, antivirus programs.

Nothing much we can do about that.

You'll have to turn off/allow your AV to download and install/run it.

What particular AV is is?

**Comment by booiiing** [comment]
I'm using Windows Defender, so that could be a common problem.

**Comment by robbyxp1** [comment]
I did, via chrome, and it said 'its not commonly downloaded' , but you could override.

then it installed okay.

**Comment by booiiing** [comment]
I'm aware that you can override, but cautious people may choose not to. I thought there could be a nice fix for it ;)

**Comment by robbyxp1** [comment]
Thanks. Unfortunately there is no rhyme of reason to when each AV signals a problem.  

I do one version, then another, mostly the same, and the different AVs change their mind all the time.  The more obscure ones tend to be the most touchy.

And you can't really fix it, as its mostly heuristics picking it up, and i can't go around changing the whole thing just because 1 AV does not like a certain package of code.

thanks for the report.
