### ISSUE TITLE
the canonn plugin is not working properly

### ISSUE THREAD

**Issue by GALDART** [EDDiscovery/EDD-EDMC#6]
the canonn plugin is not working to some versions.
using canonn pluguin with EDMC everything works normally, but using in EDDiscovery via EDD-EDMC does not work properly.

at the moment I am using the latest version of both EDD-EDMC 1.2.0 and  EDMC-Canonn 5.26.0, EDDiscovery Release12.0.2.

<a href="https://imgur.com/TshrOx6"><img src="https://i.imgur.com/TshrOx6.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/m8arXJ5"><img src="https://i.imgur.com/m8arXJ5.png" title="source: imgur.com" /></a>

**Comment by Eahlstan** [comment]
The newer versions of the canonn plugin use things that are present in newer EDMC versions but not in the version EDD-EDMC forked.
Robby is aware of this and said he'll update it when he has the time.

On a personal note: EDD-EDMC was made at a time where it seemed like that EDMC was going to be abandoned and Robby thought that would be bad. EDMC has made a complete return since this, so personally I think it's better to use the original EDMC as it's better maintained than EDD-EDMC and apart from starting and closing with EDDiscovery there's nothing EDD-EDMC does better than EDMC. If you can use EDMC I'd prefer it over EDD-EDMC at all times.
(Sorry Robby)

**Comment by robbyxp1** [comment]
I know.

To be honest, EDMC is a constantly moving target with a leaky and poorly defined API definition which makes it harder for me to emulate. Hopefully the new API interface the EDMC team is inventing will make it easier.

And if you want to use EDMC be my guest.  95% of its use cases are already in EDD with a better interface ;-) only a few of them (such as Cannon) is not covered!  And thats not a big enough use case for it to be in EDD.

So for now, I'm not concerned that cannon will not work. In the future, when EDMC improves its API it may do.

**Comment by KnightArch** [comment]
Thank you for the response, Galdart and I have been trying to figure out with LCU No Fool Like One from Cannon Research how to get the plugin working again but LCU can do nothing. Would be better if the cannon plugin was integrated directly in the Discovery  but I don't believe it's a easy move. I have some troubles with the new version of EDMC as well and EDD-EDMC was working fine until they change the API a few months ago and since then I'm no longer able to use the cannon plugin. I personally don't know the guys who develop any of the other tools but if we could reach everyone and try to integrate the stuff or at least get a standardized API so all the tools work well together, would be a pretty nice addition to the community in general. Again, thank you for your response, both of you!
